---
title: "data_science_load_data"
author: "Alina Levine"
date: "April 2, 2019"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(tidyverse)
library(haven)

```

#Demographics variables

sequence number, hispanic ethnicity, age,Ttotal household income

https://wwwn.cdc.gov/nchs/nhanes/search/variablelist.aspx?Component=Demographics&CycleBeginYear=2015

```{r}
demographics = read_xpt("data/demographics.XPT") %>% janitor::clean_names()

```


#blood pressure and cholesterol
ever told you have high blood pressure, doctor ever told you have high cholesterol

https://wwwn.cdc.gov/Nchs/Nhanes/2015-2016/BPQ_I.htm

```{r}

lookup.xport("data/BPQ_I.xpt")

bp_chol = read.xport("data/BPQ_I.xpt") %>%
  select(SEQN, BPQ020, BPQ080)

```


# Body Measure

```{r}
lookup.xport("data/body_measures.xpt")

body_measures = 
  read_xpt("data/body_measures.xpt") %>% 
  select(SEQN, 
         bmi = BMXBMI)

# proportion of missing value
sum(is.na(body_measures$bmi))/length(body_measures$SEQN)
                                    
```



# Diet Behavior and Nutrition

```{r}
lookup.xport("data/diet.xpt")

diet_behavior =
  read_xpt("data/diet.xpt") %>% 
  select(SEQN, 
         fast = DBD900, 
         ready = DBD905, 
         forzen = DBD910) 

# proportion of missing value
sum(is.na(diet_behavior$fast))/length(diet_behavior$SEQN)
sum(is.na(diet_behavior$ready))/length(diet_behavior$SEQN)
sum(is.na(diet_behavior$forzen))/length(diet_behavior$SEQN)
```


# Diabetes

```{r}
lookup.xport("data/diabetes.xpt")

diabetes =
  read_xpt("data/diabetes.xpt") %>% 
  select(SEQN, 
         diabete = DIQ010)

# proportion of missing value
sum(is.na(diabetes$diabete))/length(diabetes$SEQN)
```

# Medical Conditions

```{r}
lookup.xport("data/medical_cond.xpt")

medical_cond =
  read_xpt("data/medical_cond.xpt") %>% 
  select(SEQN, 
         overweight = MCQ080, 
         gout = MCQ160N) 


# proportion of missing value
sum(is.na(medical_cond$overweight))/length(medical_cond$SEQN)
sum(is.na(medical_cond$gout))/length(medical_cond$SEQN)
```


# Response

```{r}
coronary = 
  read_xpt("data/medical_cond.xpt") %>% 
  select(SEQN, 
         disease = MCQ160C) 

# proportion of missing value
sum(is.na(coronary$disease))/length(coronary$SEQN)
```

