---
title: "Pre_XueYang"
author: "Xue Yang"
date: "4/4/2019"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(tidyverse)
library(haven)
```


# Diabetes

```{r}
lookup.xport("data/diabetes.xpt")

diabetes =
  read_xpt("data/diabetes.xpt") %>% 
  select(SEQN, 
         diabete = DIQ010) %>% 
  mutate(diabete = ifelse(!(diabete %in% c(1,2,3)), NA, diabete))

# proportion of missing value
sum(is.na(diabetes$diabete))/length(diabetes$SEQN)
```


# Medical Conditions

```{r}
lookup.xport("data/medical_cond.xpt")

medical_cond =
  read_xpt("data/medical_cond.xpt") %>% 
  select(SEQN, 
         overweight = MCQ080, 
         gout = MCQ160N) %>% 
  mutate(overweight = ifelse(!(overweight %in% c(1,2)), NA, overweight),
         gout = ifelse(!(gout %in% c(1,2)), NA, gout))


# proportion of missing value
sum(is.na(medical_cond$overweight))/length(medical_cond$SEQN)
sum(is.na(medical_cond$gout))/length(medical_cond$SEQN)
```

# Diet Behavior and Nutrition

```{r}
lookup.xport("data/diet.xpt")

diet_behavior =
  read_xpt("data/diet.xpt") %>% 
  select(SEQN, 
         fast = DBD900, 
         ready = DBD905, 
         forzen = DBD910) %>% 
  filter(!fast %in% c(5555, 7777, 9999),
         !ready %in% c(6666, 7777, 9999),
         !forzen %in% c(6666, 7777, 9999))


# proportion of missing value
sum(is.na(diet_behavior$fast))/length(diet_behavior$SEQN)
sum(is.na(diet_behavior$ready))/length(diet_behavior$SEQN)
sum(is.na(diet_behavior$forzen))/length(diet_behavior$SEQN)
```

# Body Measure

```{r}
body_measures = 
  read_xpt("data/body_measures.xpt") %>% 
  select(SEQN, 
         bmi = BMXBMI)

# proportion of missing value
sum(is.na(body_measures$bmi))/length(body_measures$SEQN)
```


# Response

```{r}
coronary = 
  read_xpt("data/medical_cond.xpt") %>% 
  select(SEQN, 
         disease = MCQ160C) %>% 
  mutate(disease = ifelse(!(disease %in% c(1,2)), NA, disease))

# proportion of missing value
sum(is.na(coronary$disease))/length(coronary$SEQN)
```



